[package]
name = "Visionb8_Rebase"
version = "0.1.0"
authors = ["TheKayneGame <Kayne.saridjo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name="visionb8"
crate-type = ["dylib"]

[dependencies]
image = "0.21.1"